#+TITLE: Middlewarez
#+AUTHOR: owickstrom

* Design

** Connection

A connection models the entirety of a connection between the HTTP server and
the user agent - both request and response. This design is adopted from /Plug/,
an abstract HTTP interface in Elixir, that enables various HTTP libraries to
inter-operate.


* Use Cases

** Writing a Full Response

A function which writes a complete response could take a connection with an
empty response.

#+BEGIN_SRC purescript
  class ResponseWriter w where
    writeResponse :: String
                  -> w
                  -> Conn { response :: Complete }

  instance ∀ r. ResponseWriter (Conn { response :: Empty } | r) where
    writeResponse r conn = ...
#+END_SRC

** Writing a Partial Response

A function which writes a partial response could take a connection of either an
empty or a partial response.

#+BEGIN_SRC purescript
  class PartialWriter w where
    writePartial :: String
                 -> w
                 -> Conn { response :: Partial }
#+END_SRC

** Parsing the Request Body

The request body is a stream in the connection. It might not always be
of interest, thus it is not read, and not parsed, by default. Instead,
the user explicitly chooses to read and parse the body with a given
parser, which returns a new connection of a type reflecting this
change.

#+BEGIN_SRC purescript
  class BodyParser t p where
    parse ∷ ∀ r. Conn { bodyStream ∷ Stream Unconsumed | r }
            → Conn { bodyStream ∷ Stream Consumed, body ∷ t | r }

  instance BodyParser Form HttpFormParamsParser where
    parse conn = ...
#+END_SRC
